config/routes.rb
Aws::Application.routes.draw do

  resources :my_records

end

app/models/my_record.rb
class MyRecord < AWS::Record::Base
	string_attr :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/my_records_controller.rb
class MyRecordsController < ApplicationController
  # GET /my_records
  # GET /my_records.json
  def index
    @my_records = MyRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @my_records }
    end
  end

  # GET /my_records/1
  # GET /my_records/1.json
  def show
    @my_record = MyRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @my_record }
    end
  end

  # GET /my_records/new
  # GET /my_records/new.json
  def new
    @my_record = MyRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @my_record }
    end
  end

  # GET /my_records/1/edit
  def edit
    @my_record = MyRecord.find(params[:id])
  end

  # POST /my_records
  # POST /my_records.json
  def create
    @my_record = MyRecord.new(params[:my_record])

    respond_to do |format|
      if @my_record.save
        format.html { redirect_to @my_record, notice: 'My record was successfully created.' }
        format.json { render json: @my_record, status: :created, location: @my_record }
      else
        format.html { render action: "new" }
        format.json { render json: @my_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /my_records/1
  # PUT /my_records/1.json
  def update
    @my_record = MyRecord.find(params[:id])

    respond_to do |format|
      if @my_record.update_attributes(params[:my_record])
        format.html { redirect_to @my_record, notice: 'My record was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @my_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_records/1
  # DELETE /my_records/1.json
  def destroy
    @my_record = MyRecord.find(params[:id])
    @my_record.destroy

    respond_to do |format|
      format.html { redirect_to my_records_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_records_helper.rb
module MyRecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aws</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/my_records/_form.html.erb
<%= form_for(@my_record) do |f| %>
  <% if @my_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_record.errors.count, "error") %> prohibited this my_record from being saved:</h2>

      <ul>
      <% @my_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_records/edit.html.erb
<h1>Editing my_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_record %> |
<%= link_to 'Back', my_records_path %>

app/views/my_records/index.html.erb
<h1>Listing my_records</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @my_records.each do |my_record| %>
  <tr>
    <td><%= my_record.name %></td>
    <td><%= link_to 'Show', my_record %></td>
    <td><%= link_to 'Edit', edit_my_record_path(my_record) %></td>
    <td><%= link_to 'Destroy', my_record, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New My record', new_my_record_path %>

app/views/my_records/new.html.erb
<h1>New my_record</h1>

<%= render 'form' %>

<%= link_to 'Back', my_records_path %>

app/views/my_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @my_record.name %>
</p>


<%= link_to 'Edit', edit_my_record_path(@my_record) %> |
<%= link_to 'Back', my_records_path %>